# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf3d5580670e941686078737ab5d09da67728fb01a02803d04001d205579e76f473e4501919b36ce105022064bd14d1761acc0860bb2a0cd6742d4bcee085d4

test:
  secret_key_base: 97700a8ccd2cfd2e7d194f960d4da7e9b42568e03dbbff36382e694585548509f598e0919f8837e1939ebe2fd62f58310cead4f68f411e23f868bc0c8715498a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
